version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    cap_add:
      - SYS_NICE

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "6c744e2d03335dcd2b877291bdbf551fa00d9e9f69ca1ddb24f3a5e9881c30621774313d95a33ecdffe21aefcab7edc89ed5dba9d7be1865e024fd546ff9342d"
    tty: true
    stdin_open: true

  web:
    build: ./nginx
    volumes:
      - ./public:/usr/share/nginx/public
    ports:
      - 80:80
    depends_on:
      - app
